name: Call docker-registry Workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: datatest067/saiproject/.github/workflows/docker-registry.yaml@master
    with:
      image-name: 'jmeter'
      registry: 'docker.io'  # Example: Docker Hub registry
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    # secrets:
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

