service_name                   = "greenfield-main"
env                            = "dev"
vpc_id                         = "vpc-0112db0a42976430a"
task_role_name                 = "greenfield-main"
domain_name                    = "platform-sso.dev.blastpoint.com"
external                       = false
vpc_subnet_ids                 = ["subnet-05387ad016b59b1ce", "subnet-0c62a13f520711400"]
target_group_name              = "greenfield-main"
container_port                 = "80"
ssl_redirect                   = true
redis_name                     = "greenfield-main"
elasticache_instance_type      = "cache.t3.medium"
elasticache_availability_zones = ["us-east-2a", "us-east-2b", "us-east-2c"]
elasticache_engine_version     = "6.2.6"
container_name                 = "greenfield-main"
image                          = ""
region                         = "us-east-2"
log_stream_name                = "greenfield-main"
elb_name                       = "greenfield-main"
certificate_sans               = [""]
sentry_flask_dsn               = "https://1c52f107816c49848a487501e53a2cc1@o1080417.ingest.sentry.io/6249444"
